package com.example.localization

object StringsLocalization {

  fun get(key: String, lang: String): String {
    val languageMap = when (lang.lowercase()) {
      "es" -> spanishStrings
      "fr" -> frenchStrings
      "de" -> germanStrings
      "hi" -> hindiStrings
      else -> englishStrings
    }
    return languageMap[key] ?: englishStrings[key] ?: key
  }

  data class LanguageItem(val code: String, val name: String)

  val availableLanguages = listOf(
    LanguageItem("en", "English"),
    LanguageItem("es", "Español"),
    LanguageItem("fr", "Français"),
    LanguageItem("de", "Deutsch"),
    LanguageItem("hi", "हिन्दी")
  )

  private val englishStrings = mapOf(
    "app_name" to "NutriTrack",
    "nav_dashboard" to "Dashboard",
    "nav_log" to "Food Database",
    "nav_analytics" to "Analytics",
    "nav_plans" to "Diet Plans",
    "nav_profile" to "Profile",
    "calories_remaining" to "Remaining",
    "calories_consumed" to "Food Consumed",
    "calories_burned" to "Wearable Burned",
    "daily_budget" to "Daily Target",
    "protein" to "Protein",
    "carbs" to "Carbs",
    "fat" to "Fat",
    "fiber" to "Fiber",
    "water" to "Hydration",
    "glasses" to "glasses",
    "breakfast" to "Breakfast",
    "lunch" to "Lunch",
    "dinner" to "Dinner",
    "snack" to "Snacks",
    "add_food" to "Log Food",
    "wearable_connected" to "Wearable Connected",
    "sync_now" to "Sync Now",
    "synced_just_now" to "Synced moments ago",
    "weekly_report" to "Weekly Health Report",
    "health_trends" to "Intake & Energy Trends",
    "food_alternatives" to "Healthier Food Swaps",
    "save_calories" to "Save Calorie Spikes",
    "swap_now" to "Recommended Swap",
    "macro_distribution" to "Macro Breakdown",
    "weight_progress" to "Weight Progress",
    "cloud_backup" to "Cloud Sync & Backup",
    "backup_now" to "Backup Now",
    "metric" to "Metric (kg, cm, ml)",
    "imperial" to "Imperial (lbs, in, oz)",
    "milestones" to "Achievements & Milestones",
    "share_milestone" to "Share Milestone",
    "custom_food" to "Add Custom Food",
    "offline_ready" to "Offline Mode: 100% Active"
  )

  private val spanishStrings = mapOf(
    "app_name" to "NutriTrack",
    "nav_dashboard" to "Panel",
    "nav_log" to "Base Alimentos",
    "nav_analytics" to "Análisis",
    "nav_plans" to "Dietas",
    "nav_profile" to "Perfil",
    "calories_remaining" to "Restantes",
    "calories_consumed" to "Consumidas",
    "calories_burned" to "Quemadas Reloj",
    "daily_budget" to "Meta Diaria",
    "protein" to "Proteína",
    "carbs" to "Carbohidratos",
    "fat" to "Grasa",
    "fiber" to "Fibra",
    "water" to "Hidratación",
    "glasses" to "vasos",
    "breakfast" to "Desayuno",
    "lunch" to "Almuerzo",
    "dinner" to "Cena",
    "snack" to "Snacks",
    "add_food" to "Registrar Comida",
    "wearable_connected" to "Reloj Conectado",
    "sync_now" to "Sincronizar",
    "synced_just_now" to "Sincronizado ahora",
    "weekly_report" to "Informe Semanal",
    "health_trends" to "Tendencias Nutricionales",
    "food_alternatives" to "Alternativas Saludables",
    "save_calories" to "Ahorra Calorías",
    "swap_now" to "Cambio Recomendado",
    "macro_distribution" to "Distribución Macros",
    "weight_progress" to "Progreso de Peso",
    "cloud_backup" to "Copia en la Nube",
    "backup_now" to "Respaldar Ahora",
    "metric" to "Métrico (kg, cm, ml)",
    "imperial" to "Imperial (lbs, in, oz)",
    "milestones" to "Logros y Metas",
    "share_milestone" to "Compartir Logro",
    "custom_food" to "Crear Alimento",
    "offline_ready" to "Modo Offline Activo"
  )

  private val frenchStrings = mapOf(
    "app_name" to "NutriTrack",
    "nav_dashboard" to "Tableau",
    "nav_log" to "Aliments",
    "nav_analytics" to "Analyses",
    "nav_plans" to "Régimes",
    "nav_profile" to "Profil",
    "calories_remaining" to "Restantes",
    "calories_consumed" to "Consommées",
    "calories_burned" to "Brûlées Montre",
    "daily_budget" to "Objectif Quotidien",
    "protein" to "Protéines",
    "carbs" to "Glucides",
    "fat" to "Lipides",
    "fiber" to "Fibres",
    "water" to "Hydratation",
    "glasses" to "verres",
    "breakfast" to "Petit-déjeuner",
    "lunch" to "Déjeuner",
    "dinner" to "Dîner",
    "snack" to "Collation",
    "add_food" to "Ajouter Repas",
    "wearable_connected" to "Montre Connectée",
    "sync_now" to "Synchroniser",
    "synced_just_now" to "Synchronisé à l'instant",
    "weekly_report" to "Rapport Hebdomadaire",
    "health_trends" to "Tendances Santé",
    "food_alternatives" to "Alternatives Saines",
    "save_calories" to "Économisez des Calories",
    "swap_now" to "Échange Recommandé",
    "macro_distribution" to "Répartition Macros",
    "weight_progress" to "Évolution du Poids",
    "cloud_backup" to "Sauvegarde Cloud",
    "backup_now" to "Sauvegarder",
    "metric" to "Métrique (kg, cm, ml)",
    "imperial" to "Impérial (lbs, in, oz)",
    "milestones" to "Succès & Jalons",
    "share_milestone" to "Partager le Succès",
    "custom_food" to "Créer un Aliment",
    "offline_ready" to "Mode Hors-ligne Actif"
  )

  private val germanStrings = mapOf(
    "app_name" to "NutriTrack",
    "nav_dashboard" to "Übersicht",
    "nav_log" to "Nahrung",
    "nav_analytics" to "Berichte",
    "nav_plans" to "Ernährungsplan",
    "nav_profile" to "Profil",
    "calories_remaining" to "Verbleibend",
    "calories_consumed" to "Aufgenommen",
    "calories_burned" to "Smartwatch Verbrannt",
    "daily_budget" to "Tagesziel",
    "protein" to "Eiweiß",
    "carbs" to "Kohlenhydrate",
    "fat" to "Fett",
    "fiber" to "Ballaststoffe",
    "water" to "Wasser",
    "glasses" to "Gläser",
    "breakfast" to "Frühstück",
    "lunch" to "Mittagessen",
    "dinner" to "Abendessen",
    "snack" to "Snacks",
    "add_food" to "Mahlzeit eintragen",
    "wearable_connected" to "Smartwatch Verbunden",
    "sync_now" to "Synchronisieren",
    "synced_just_now" to "Gerade synchronisiert",
    "weekly_report" to "Wochenbericht",
    "health_trends" to "Gesundheitstrends",
    "food_alternatives" to "Gesunde Alternativen",
    "save_calories" to "Kalorien Sparen",
    "swap_now" to "Empfohlener Tausch",
    "macro_distribution" to "Makro-Verteilung",
    "weight_progress" to "Gewichtsverlauf",
    "cloud_backup" to "Cloud-Sicherung",
    "backup_now" to "Jetzt Sichern",
    "metric" to "Metrisch (kg, cm, ml)",
    "imperial" to "Imperial (lbs, in, oz)",
    "milestones" to "Meilensteine",
    "share_milestone" to "Erfolg Teilen",
    "custom_food" to "Eigenes Lebensmittel",
    "offline_ready" to "Offline-Modus Bereit"
  )

  private val hindiStrings = mapOf(
    "app_name" to "NutriTrack",
    "nav_dashboard" to "डैशबोर्ड",
    "nav_log" to "आहार सूची",
    "nav_analytics" to "प्रगति रिपोर्ट",
    "nav_plans" to "डाइट प्लान",
    "nav_profile" to "प्रोफाइल",
    "calories_remaining" to "शेष कैलोरी",
    "calories_consumed" to "कुल आहार",
    "calories_burned" to "घड़ी से बर्न",
    "daily_budget" to "दैनिक लक्ष्य",
    "protein" to "प्रोटीन",
    "carbs" to "कार्ब्स",
    "fat" to "वसा (फैट)",
    "fiber" to "फाइबर",
    "water" to "पानी की मात्रा",
    "glasses" to "गिलास",
    "breakfast" to "नाश्ता",
    "lunch" to "दोपहर का खाना",
    "dinner" to "रात का खाना",
    "snack" to "स्नैक्स",
    "add_food" to "भोजन जोड़ें",
    "wearable_connected" to "स्मार्टवॉच कनेक्टेड",
    "sync_now" to "सिंक करें",
    "synced_just_now" to "अभी सिंक हुआ",
    "weekly_report" to "साप्ताहिक रिपोर्ट",
    "health_trends" to "स्वास्थ्य रुझान",
    "food_alternatives" to "स्वस्थ विकल्प",
    "save_calories" to "कैलोरी बचाएं",
    "swap_now" to "सुझाया गया विकल्प",
    "macro_distribution" to "मैक्रो विवरण",
    "weight_progress" to "वजन की प्रगति",
    "cloud_backup" to "क्लाउड बैकअप",
    "backup_now" to "अभी बैकअप लें",
    "metric" to "मीट्रिक (किग्रा, सेमी)",
    "imperial" to "इम्पीरियल (पाउंड, इंच)",
    "milestones" to "उपलब्धियां",
    "share_milestone" to "शेयर करें",
    "custom_food" to "नया आहार जोड़ें",
    "offline_ready" to "ऑफ़लाइन मोड सक्रिय"
  )
}
